// hycal_shower_profile.cpp
// An example of how to access the HyCal module channels' peak information
// and group them into clusters, and then analyze the shower profile of each cluster.
// This need to read the raw_replay root file (prad_<run_num(025666)>.*****_raw.root)
// which is generated by replay_rawdata.cpp with the peak analysis option (-p) enabled. 
// The raw_replay root file contains the peak information of each module channel, 
// which is necessary for the shower profile analysis.
// will do reconstruction in this code and then to analyze event by event

#include "Replay.h"
#include "PhysicsTools.h"
#include "MatchingTools.h"
#include "HyCalSystem.h"
#include "HyCalCluster.h"
#include "GemSystem.h"
#include "WaveAnalyzer.h"
#include "EventData.h"
#include "EventData_io.h"
#include "InstallPaths.h"
#include "load_daq_config.h"
#include "RunInfoConfig.h"
#include "gain_factor.h"
#include "PulseTemplateStore.h"
#include "PipelineBuilder.h"

#include <TFile.h>
#include <TH1F.h>
#include <TH2Poly.h>
#include <TChain.h>
#include <TFitResult.h>
#include <TFile.h>
#include <TText.h>

#include <iostream>
#include <fstream>
#include <iomanip>
#include <string>
#include <cstdlib>
#include <getopt.h>
#include <filesystem>
#include <vector>
#include <memory>
#include <algorithm>
#include <map>
#include <queue>
#include <set>
#include <utility>
#include <cmath>
#include <TMatrixD.h>
#include <TVectorD.h>
#include <TDecompSVD.h>

#include <nlohmann/json.hpp>

#ifndef DATABASE_DIR
#define DATABASE_DIR "."
#endif

namespace fs = std::filesystem;

using EventVars = prad2::RawEventData;
using namespace analysis;

// ── File collection helper ───────────────────────────────────────────────────
static std::vector<std::string> collectRootFiles(const std::string &path)
{
    std::vector<std::string> files;
    if (fs::is_directory(path)) {
        for (auto &entry : fs::directory_iterator(path)) {
            if (entry.is_regular_file() &&
                entry.path().filename().string().find("_raw.root") != std::string::npos)
                files.push_back(entry.path().string());
        }
        std::sort(files.begin(), files.end());
    } else {
        files.push_back(path);
    }
    return files;
}

// ── Main ─────────────────────────────────────────────────────────────────────
int main(int argc, char *argv[])
{
    std::string db_dir = prad2::resolve_data_dir(
        "PRAD2_DATABASE_DIR",
        {"../share/prad2evviewer/database"},
        DATABASE_DIR);
    if (const char *env = std::getenv("PRAD2_DATABASE_DIR")) db_dir = env;

    // ── Argument parsing ─────────────────────────────────────────────────────
    std::string output_path_name, daq_config_file, recon_config_file, gem_ped_file;
    int  max_events  = -1;
    int  num_threads = 4;
    int  num_files   = -1;

    int opt;
    while ((opt = getopt(argc, argv, "o:n:f:j:")) != -1) {
        switch (opt) {
            case 'o': output_path_name = optarg; break;
            case 'n': max_events       = std::atoi(optarg); break;
            case 'f': num_files        = std::atoi(optarg); break;
            case 'j': num_threads     = std::atoi(optarg); break;
        }
    }

    // Collect all input files
    std::vector<std::string> root_files;
    for (int i = optind; i < argc; ++i) {
        auto f = collectRootFiles(argv[i]);
        if (num_files > 0) {
            int remaining = num_files - static_cast<int>(root_files.size());
            if (remaining <= 0) break;
            int take = std::min(remaining, static_cast<int>(f.size()));
            root_files.insert(root_files.end(), f.begin(), f.begin() + take);
            if (static_cast<int>(root_files.size()) >= num_files) break;
        } else {
            root_files.insert(root_files.end(), f.begin(), f.end());
        }
    }
    if (root_files.empty()) {
        std::cerr << "No input files specified.\n";
        std::cerr << "Usage: hycal_shower_profile <input_raw.root|dir> [more...] "
                     "[-o ./output_name(no extension)] [-n max_events] [-f nfiles] [-j threads]\n";
        return 1;
    }

    if (output_path_name.empty()) {
        std::cerr << "No output prefix provided. Please pass -o <output_prefix>.\n";
        return 1;
    }

    TChain tree("events");
    for (const auto &file : root_files) {
        tree.Add(file.c_str());
    }

    EventVars ev;
    prad2::SetRawReadBranches(&tree, ev);

    int run_num = get_run_int(root_files.front());
    gRunConfig = LoadRunConfig(db_dir + "/runinfo/general.json", run_num);
    recon_config_file = db_dir + "/reconstruction_config.json";
    daq_config_file = db_dir + "/daq_config.json";

    evc::DaqConfig daq_cfg;

    // Detectors: PRad-II flows through PipelineBuilder so the wiring stays in
    // one place (see prad2det/include/PipelineBuilder.h).
    fdec::HyCalSystem                 hycal;
    gem::GemSystem                    gem_sys;
    fdec::ClusterConfig               cluster_cfg;
    prad2::HyCalTimeCuts              hc_time_cuts;
    prad2::HyCalRfOffsets             hc_rf_offsets;
    DetectorTransform                 hycal_transform;
    std::array<DetectorTransform, 4>  gem_transforms;
    std::unordered_map<int, int>      roc_to_crate;
    int                               match_method = 1;

    prad2::Pipeline pipeline = prad2::PipelineBuilder()
        .set_database_dir(db_dir)
        .set_recon_config(recon_config_file)
        .set_daq_config(daq_config_file)
        .set_gem_pedestal(gem_ped_file)     // empty falls back to RunConfig default
        .set_run_number(run_num)
        .set_log_stream(&std::cerr)
        .build();

    daq_cfg          = std::move(pipeline.daq_cfg);
    hycal            = std::move(pipeline.hycal);
    gem_sys          = std::move(pipeline.gem);
    cluster_cfg      = pipeline.hycal_cluster_cfg;
    hc_time_cuts     = std::move(pipeline.hycal_time_cuts);
    hc_rf_offsets    = std::move(pipeline.hycal_rf_offsets);
    hycal_transform  = pipeline.hycal_transform;
    gem_transforms   = pipeline.gem_transforms;
    match_method     = pipeline.match_method;

    fdec::HyCalCluster   clusterer(hycal);
    clusterer.SetConfig(cluster_cfg);
    gem::GemCluster      gem_clusterer;
    MatchingTools        matching(match_method);

    //initialize tools for cluster reconstruction
    fdec::WaveAnalyzer ana(daq_cfg.wave_cfg);
    fdec::PulseTemplateStore template_store;
    if (daq_cfg.wave_cfg.nnls_deconv.enabled
        && !daq_cfg.wave_cfg.nnls_deconv.template_file.empty()) {
        template_store.LoadFromFile(
            db_dir + "/" + daq_cfg.wave_cfg.nnls_deconv.template_file,
            daq_cfg.wave_cfg);
    }
    ana.SetTemplateStore(&template_store);
    fdec::WaveResult wres;

    auto gain_corr_ts = prad2::LoadGainCorrTimeSeries(
        gRunConfig.gain_data_dir + "/gain_correction", run_num);

    // create histograms you want to fill for shower profile analysis
    TH1F *h1_cluster_energy = new TH1F("h1_cluster_energy", "Cluster Energy;Energy [MeV];Counts", 4000, 0, 4000);
    TH1F *h1_seed_energy = new TH1F("h1_seed_energy", "Seed Module Energy;Energy [MeV];Counts", 4000, 0, 4000);
    TH2F *h2_cluster_vs_seed_energy = new TH2F("h2_cluster_vs_seed_energy", 
        "Cluster Energy vs Seed Module Energy;Seed Energy [MeV];Cluster Energy [MeV]", 
        4000, 0, 4000, 4000, 0, 4000);
    TH1F *h1_blocks_1st_layer = new TH1F("h1_blocks_1st_layer", "Number of Fired Modules in 1st Layer;Count;Events", 20, 0, 20);
    TH1F *h1_blocks_2nd_layer = new TH1F("h1_blocks_2nd_layer", "Number of Fired Modules in 2nd Layer;Count;Events", 20, 0, 20);
    TH1F *h1_time_diff_seed = new TH1F("h1_time_diff_seed", "Time Difference with Seed Module;#Delta t [ns];Events", 200, -10, 10);

    // Here loop over the events in the TChain, read channels data, reconstruct clusters, and fill the histograms
    long long nentries = tree.GetEntries();
    for (long long i = 0; i < nentries; ++i) {
        tree.GetEntry(i);
        if (i >= max_events && max_events > 0) break;
        if (i % 10000 == 0) std::cout << "Processed " << i << " / " << nentries << " entries.\r" << std::flush;

        // assume you are selecting Mott-like events with a single cluster in the HyCal
        if ((ev.trigger_bits & prad2::TBIT_sum) == 0) continue;
        if (ev.nch > 70) continue; // channel numbers too high, likely not a clean event

        // Reconstruct clusters for this event.
        clusterer.Clear();

        // Per-event gain correction (time-series lookup by event number).
        const auto &gain_corr = gain_corr_ts.GetCorr(static_cast<int>(ev.event_num));

        for (int j = 0; j < ev.nch; ++j) {
            const auto *mod = hycal.module_by_id(ev.module_id[j]);
            if (!mod || !mod->is_pwo4()) continue;

            // Per-ID gain correction: average of three LMS channels.
            const float gain = (mod->id > 1000)
                ? (gain_corr.w[mod->id - 1000].corr[1] + gain_corr.w[mod->id - 1000].corr[2]) / 2.0f
                : 1.0f; // default gain factor
            // timing offset for this module
            float time_offset = mod->time_offset;

            const auto hc_win = hc_time_cuts.at(mod->index);
            // Multi-pulse mode: push every peak inside the trigger
            // window into the clusterer; the seed-anchored timing
            // coincidence cut is applied inside HyCalCluster, 
            // maximum 2 ns difference between pulses in a same cluster.
            for (int p = 0; p < ev.npeaks[j]; ++p) {
                float peak_time = ev.peak_time[j][p] - time_offset; // apply module time offset
                if (peak_time <= hc_win.lo) continue;
                if (peak_time >= hc_win.hi) continue;
                float adc = ev.peak_integral[j][p] * gain;
                float energy = static_cast<float>(mod->energize(adc));
                clusterer.AddHit(mod->index, energy, peak_time);
            }
        }
        clusterer.FormClusters();
        std::vector<fdec::ClusterHit> hits;
        clusterer.ReconstructHits(hits);

        // Here could also reconstruct the GEM parts do matching with HyCal clusters if needed
        // TODO: Add GEM cluster reconstruction and matching if needed

        // select single cluster Mott events
        float hc_x = hits[0].x, hc_y = hits[0].y, hc_z = gRunConfig.hycal_z;
        float theta = std::atan2(std::sqrt(hc_x * hc_x + hc_y * hc_y), hc_z) * 180.0 / M_PI;
        if (hits.size() != 1 || hits[0].nblocks < 3) continue;
        if (std::abs(hits[0].energy - gRunConfig.Ebeam) > 3. * 0.033 * std::sqrt(gRunConfig.Ebeam * 1000.)) continue;
        if (theta < 0.7 ) continue; 

        int seed_id = hits[0].center_id;
        const auto *seed_mod = hycal.module_by_id(seed_id);
        if (!seed_mod || !seed_mod->is_pwo4()) continue;

        //the time window cut is already applied in the clusterer
        float dt_max = cluster_cfg.seed_time_window;

        // counts for fired modules in the 1st and 2nd layer of neighbors
        int n1st_layer = 0;
        int n2nd_layer = 0;

        bool seed_not_clean = false;

        // loop over the hits in the cluster
        // Here go to the event by event analysis, add more analysis code or selection .etc here
        for (int j = 0; j < ev.nch; ++j) {
            const auto *mod = hycal.module_by_id(ev.module_id[j]);
            if (!mod || !mod->is_pwo4()) continue;

            // Per-ID gain correction: average of three LMS channels.
            const float gain = (mod->id > 1000)
                ? (gain_corr.w[mod->id - 1000].corr[1] + gain_corr.w[mod->id - 1000].corr[2]) / 2.0f
                : 1.0f; // default gain factor
            // timing offset for this module
            float time_offset = mod->time_offset;

            // select the seed module and its energy (require only one peak in seed module)
            if (mod->id == seed_id) {
                if (ev.npeaks[j] != 1) {
                    seed_not_clean = true;
                    break;
                }
                float seed_energy = static_cast<float>(mod->energize(ev.peak_integral[j][0] * gain));
                h1_seed_energy->Fill(seed_energy);
                h2_cluster_vs_seed_energy->Fill(seed_energy, hits[0].energy);
            }
            // select the 1st layer of neighboring modules
            if (std::abs(mod->x - seed_mod->x) < mod->size_x * 1.5f &&
                std::abs(mod->y - seed_mod->y) < mod->size_y * 1.5f && mod->id != seed_mod->id) 
            {
                // check if this module has a peak in seed time window
                for (int p = 0; p < ev.npeaks[j]; ++p) {
                    float peak_time = ev.peak_time[j][p] - time_offset; // apply module time offset
                    float dt = peak_time - hits[0].time;
                    h1_time_diff_seed->Fill(dt);
                    if (std::abs(dt) < dt_max) {
                        n1st_layer++;
                        float energy = static_cast<float>(mod->energize(ev.peak_integral[j][p] * gain));
                        // fill the histogram for shower profile analysis

                        break; // only count one peak per module
                    }
                }
            }
            // select the 2nd layer of neighboring modules
            if (std::abs(mod->x - seed_mod->x) < mod->size_x * 2.5f &&
                std::abs(mod->y - seed_mod->y) < mod->size_y * 2.5f && 
                (std::abs(mod->x - seed_mod->x) > mod->size_x * 1.5f ||
                std::abs(mod->y - seed_mod->y) > mod->size_y * 1.5f) && mod->id != seed_mod->id) 
            {
                // check if this module has a peak in seed time window
                for (int p = 0; p < ev.npeaks[j]; ++p) {
                    float peak_time = ev.peak_time[j][p] - time_offset; // apply module time offset
                    float dt = peak_time - hits[0].time;
                    h1_time_diff_seed->Fill(dt);
                    if (std::abs(dt) < dt_max) {
                        n2nd_layer++;
                        float energy = static_cast<float>(mod->energize(ev.peak_integral[j][p] * gain));
                        // fill the histogram for shower profile analysis

                        break; // only count one peak per module
                    }
                }
            }
        }
        // fill the histograms for the number of fired modules in the 1st and 2nd layers
        if (!seed_not_clean) {
            h1_blocks_1st_layer->Fill(n1st_layer);
            h1_blocks_2nd_layer->Fill(n2nd_layer);
            h1_cluster_energy->Fill(hits[0].energy);
        }
    }

    // Save the histograms to a root file
    TFile *output_file = new TFile((output_path_name + ".root").c_str(), "RECREATE");
    h1_cluster_energy->Write();
    h1_seed_energy->Write();
    h2_cluster_vs_seed_energy->Write();
    h1_blocks_1st_layer->Write();
    h1_blocks_2nd_layer->Write();
    h1_time_diff_seed->Write();
    output_file->Close();

}